imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: false

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"


nemrod:
  endpoints:
    my_endpoint: "%nemrod_endpoint_host%:%nemrod_endpoint_port%/%nemrod_endpoint_path%"
  default_endpoint: my_endpoint
  namespaces:
    rdfs: "http://www.w3.org/2000/01/rdf-schema#"
    foaf: "http://xmlns.com/foaf/0.1/"
    #add the namespaces you need
    nobel: "http://data.nobelprize.org/resource/"
    terms: "http://data.nobelprize.org/terms/"
    dbpprop: "http://dbpedia.org/property/"
    dbpedia: "http://dbpedia.org/resource/"
    dbpediaowl: "http://dbpedia.org/ontology/"
    dcterms: "http://purl.org/dc/terms/"
    hbsko: "https://librarydata.hbs.edu/HBSKOntology/"
    skos: "http://www.w3.org/2004/02/skos/core#"

elastica:
  clients:
    default:
      host: %elasticsearch_host%
      port: %elasticsearch_port%
  indexes:
    nobel:
      client: default
      settings:
        index:
          analysis:
            analyzer:
              en:
                tokenizer: standard
      types:
        laureate:
          type: "terms:Laureate"
          frame: "@Demo/Laureate/laureate.jsonld"
        award:
          type: "terms:LaureateAward"
          frame: "@Demo/LaureateAward/laureateaward-es.jsonld"
        person:
          type: "hbsko:Person"
          frame: "@Demo/Person/person.jsonld"
